name: Run Server Tests

on:
  pull_request:
    branches:
      - main

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: server/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('server/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        working-directory: server
        run: poetry install --no-interaction --no-root

      - name: Run server tests
        working-directory: server
        run: poetry run pytest
